### ISSUE TITLE
Chapter Download and Delete Issue with Two-Way Sync with Anilist

### ISSUE THREAD

**Issue by imeed166** [Saud-97/TachiyomiS97#4]
### Describe your suggested feature

I have the option enabled to download new chapters and delete them when marked as read.
I have enabled two-way sync with anilist.
When I sync my library, even though the new chapter is marked as read by the extension, the app still downloads the chapter and doesn't delete it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiS97 have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/saud-97/TachiyomiS97/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Saud-97** [comment]
This is the intended behavior. Since the app expects you to read the chapter after it was released. But since you read it elsewhere this happens.

I believe you can solve this issue by enabling "Remove after read". Eventually whenever you read a chapter in the app it will check previous chapters and delete them if they were downloaded.

![image](https://github.com/Saud-97/TachiyomiS97/assets/39028181/ad5db40d-60a5-48bd-a247-1895fda13898)

Let me know if this worked for you.

**Comment by imeed166** [comment]
Good alternative solution, thank you for pointing me into this direction.
