### ISSUE TITLE
Bug in update library 

### ISSUE THREAD

**Issue by kaisanti** [Saud-97/TachiyomiS97#9]
### Steps to reproduce

bug in update library 

### Expected behavior

bug in update library 

### Actual behavior

bug in update library 

### TachiyomiS97 version

TachiyomiS97 v1.7.3

### Android version

Android 11

### Device

Redmi Note 8 Pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/saud-97/TachiyomiS97/releases/latest)**.
- [X] I have updated all installed extensions.

**Comment by Saud-97** [comment]
You have to clarify and explain otherwise I can't understand what bug are you talking about

**Comment by Saud-97** [comment]
I have checked and found that my only change regarding library update compared to J2K is that I do faster library updates by updating ~5 manga at a time instead of 1 at a time. If there were any errors it would show up in the notifications.

So for now:

- Send the error that show up in notification (if its shown) and also share the crash logs from Settings>Advanced>Dump crash logs.
- Try to update library by category instead of the global library update. See if that helps.

**Comment by Saud-97** [comment]
Can you try these steps as it might help:

- Send the error that show up in notification (if its shown) and also share the crash logs from Settings>Advanced>[Dump crash logs].
- Try to update library by category one by one instead of the global library update. See if that helps.
- Verify if your library is not updating certain manga in Settings>Library>[Skip updating titles] and [Include/Exclude Categories setting].

**Comment by Saud-97** [comment]
Will be fixed in next release.
